# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Shoreditch
tagline:          'A Jekyll theme'
description:      'A clean jekyll theme optimised for the tech blogger'
url:              https://github.com/MEHColeman/shoreditch
baseurl:          /

author:
  name:           'Mark Coleman'
  url:            'https://mehcoleman.com'
  github:         MEHColeman
  twitter:        MEHColeman
  linkedin:       MEHColeman
  instagram:      MEHColeman
  reddit:         MEHColeman
  youtube:        MEHColeman
  tiktok:         MEHColeman
  lastfm:
  dribble:
  pinterest:
  phone:          '555-0123'
  file_url:       'https://library.oapen.org/bitstream/id/370818a1-e744-4785-8ef4-6ece5ef7474c/UWP-035-REVISED.pdf'
  file_link_text: 'Brochure'
  # please split email betweed two variables. This is used as a form of
  # basic spambot protection.
  email_1:        'shoreditch@protec'
  email_2:        'ted.mehcoleman.com'

configs:
  flashy_logo:    TRUE
  round_logo:     TRUE
  logo_legend:    'Shoreditch: Something for Everyone'
  logo_location:  '/public/images/shoreditch/logo.png'
  logo_link:      'https://github.com/MEHColeman/shoreditch'

lsi:              TRUE
strict_front_matter: TRUE

paginate:         7

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: <!--more-->
      thumbnail: /public/images/shoreditch/notes.svg
      include_about: TRUE
      include_details: FALSE
  -
    scope:
      path: ""
      type: "pages"
    values:
      include_about: TRUE

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MEHColeman/shoreditch

exclude:
  - bundle
  - bundler
