# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate-v2]

# Permalinks
permalink:        pretty

# Setup
title:            Shoreditch
tagline:          'A Jekyll theme'
description:      'A clean jekyll theme optimised for the tech blogger'
url:              https://github.com/MEHColeman/shoreditch
baseurl:          /

author:
  name:           'Mark Coleman'
  url:            'https://mehcoleman.com'
  github:         MEHColeman
  twitter:        MEHColeman
  linkedin:       MEHColeman
  instagram:      MEHColeman
  reddit:         MEHColeman
  youtube:        MEHColeman
  tiktok:         MEHColeman
  lastfm:
  deviantart:
  artstation:
  phone:          '555-0123'
  file_url:       'https://library.oapen.org/bitstream/id/370818a1-e744-4785-8ef4-6ece5ef7474c/UWP-035-REVISED.pdf'
  file_link_text: 'Brochure'
  # please split email betweed two variables. This is used as a form of
  # basic spambot webcrawler protection.
  email_1:        'shoreditch@protec'
  email_2:        'ted.mehcoleman.com'

lsi:              TRUE
strict_front_matter: TRUE

# Use this line for jekyll-paginate gem, supported by github pages
# paginate:         7

# Use the following configuration if you are sticking with jekyll-paginate-v2
autopages:
  enabled: true
  collections:
    enabled: false
  tags:
    layouts:
      - autopage_tags.html
    enabled: true

pagination:
  enabled: true
  collection: 'posts'
  per_page: 7
  sort_reverse: true
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

defaults:
  -
    scope:
      path: ""
    values:
      flashy_logo: TRUE
      logo_shape: round # 'round' or 'square'
      logo_legend_shape: curved   # 'curved' or 'straight'
      logo_legend: 'Shoreditch: Something for Everyone'
      logo_location: '/public/images/shoreditch/logo.png'
      logo_link: 'https://github.com/MEHColeman/shoreditch'
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: <!--more-->
      thumbnail: /public/images/shoreditch/notes.svg
      include_sticky: TRUE
      include_logo:  FALSE
      include_details: FALSE
  -
    scope:
      path: ""
      type: "pages"
    values:
      include_sticky: TRUE
      include_logo:  FALSE
      include_details: FALSE

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MEHColeman/shoreditch

exclude:
  - bundle
  - bundler
