# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Shoreditch
tagline:          'A Jekyll theme'
description:      'A clean jekyll theme optimised for the tech blogger'
url:              https://github.com/MEHColeman/shoreditch
baseurl:          /

author:
  name:           'Mark Coleman'
  url:            'https://mehcoleman.com'

configs:
  flashy_logo:    FALSE
  round_logo:     TRUE
  logo_legend:    'Shoreditch: Something for Everyone'

lsi:              TRUE
strict_front_matter: TRUE

paginate:         7

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: <!--more-->
      thumbnail: /public/images/shoreditch/notes.svg

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MEHColeman/shoreditch

exclude:
  - bundle
  - bundler
